name: Build and deploy package
on:
  push:
    branches:
      - main

jobs:
  build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore src/LittleIdentity/LittleIdentity.csproj

      - name: Build
        run: dotnet build --no-restore src/LittleIdentity/LittleIdentity.csproj -c Release

      - name: Test
        run: dotnet test ./src/LitleIdentity.Test/LitleIdentity.Test.csproj 

      - name: Pack
        run: dotnet pack src/LittleIdentity/LittleIdentity.csproj -c Release -o ./nupkg

      - name: Push to NuGet.org
        run: dotnet nuget push "./src/LittleIdentity/bin/release/net9.0/*.nupkg" -k ${{ secrets.SECRETKEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
